### ISSUE TITLE
module Long does not match the corresponding path on disk `long`

### ISSUE THREAD

**Issue by realeatwood** [elsehow/signal-protocol#10]
pre i'm working on dva2.x.
as follow the guide , npm install signal-protocol 

i got a error:
./node_modules/signal-protocol/build/dcodeIO.js
Module not found: `/Users/eatwood/Desktop/workspace/web_version/node_modules/Long/dist/long.js` does not match the corresponding path on disk `long`.

and I found the module Long exist

**Comment by elsehow** [comment]
Hi - 

What is dva2.x?

I tried to `npm i signal-protocol` and did not encounter this error. Can you provide more details to reproduce?

**Comment by crossle** [comment]
Same problem,
Module not found: Error: [CaseSensitivePathsPlugin] `/node_modules/Long/dist/long.js` does not match the corresponding path on disk `long`.

All modules it lowcase, i dont know why signal protocol found Long

**Comment by elsehow** [comment]
@crossle 

I have again tried to `npm i signal-protocol`, and still did not encounter this error.

Please help me by providing more details to reproduce your issue. Your platform, and your version of node and npm would be helpful.
