### ISSUE TITLE
Can we use this library in react native?

### ISSUE THREAD

**Issue by vinayakb73** [elsehow/signal-protocol#11]
I like to add Signal protocol into my react native project. Is this library can use for this. If it can't, Is there any alternative available?

**Comment by moskalyk** [comment]
would like to know as well. Any Solutions? @vinayakb73

**Comment by elsehow** [comment]
I don't see why you can't use this in React Native. If you encounter a specific problem in doing so, please open an issue with the problem you're encountering.
