### ISSUE TITLE
TypeError: Cannot read property 'privKey' of undefined

### ISSUE THREAD

**Issue by DreaminDani** [elsehow/signal-protocol#6]
Hi there, I'm running into the following error when initiating a session using the signal-protocol:
```
TypeError: Cannot read property 'privKey' of undefined
    at SessionBuilder.<anonymous> (/Users/admin/projects/realtimelaw/node_modules/signal-protocol/src/SessionBuilder.js:147:66)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Here's the relevant section of my code:
```
// START Building a Session
    var address = new signal.SignalProtocolAddress('test', 0);

    // Instantiate a SessionBuilder for a remote recipientId + deviceId tuple.
    var sessionBuilder = new signal.SessionBuilder(store, address);

    // Process a prekey fetched from the server. Returns a promise that resolves
    // once a session is created and saved in the store, or rejects if the
    // identityKey differs from a previously seen identity for this address.
    store.loadIdentityKey(defaultEndpoint.registrationId).then(function(identityKey) {
      store.loadSignedPreKey(defaultEndpoint.registrationId).then(function(signedPreKey) {
        store.loadPreKey(defaultEndpoint.registrationId).then(function(preKey) {
          var signature = str2ab(defaultEndpoint.signature);
          console.log(signature)
          var promise = sessionBuilder.processPreKey({
              registrationId: defaultEndpoint.registrationId,
              identityKey: identityKey.pubKey,
              signedPreKey: {
                  keyId     : defaultEndpoint.registrationId,
                  publicKey : signedPreKey.pubKey,
                  signature : signature
              },
              preKey: {
                  keyId     : defaultEndpoint.registrationId,
                  publicKey : preKey.pubKey
              }
          });
          promise.then(function onsuccess() {
            console.log('success');
            // encrypt messages
            var plaintext = "Hello world";
            var sessionCipher = new signal.SessionCipher(store, address);
            sessionCipher.encrypt(plaintext).then(function(ciphertext) {
                // ciphertext -> { type: <Number>, body: <string> }
                handle(ciphertext.type, ciphertext.body);
            });
          });

          promise.catch(function onerror(error) {
            console.log(error);
            // handle identity key conflict
          });
        });
      });
    })
```

Any tips?

**Comment by elsehow** [comment]
hey @d3sandoval!

I am trying to run your code as a minimal, stand-alone example so I can debug.

Could you help me by showing how you are generating `defaultEndpoint`?

**Comment by DreaminDani** [comment]
@elsehow defaultEndpoint is a mongoose schema object:
I generate it with this function:
```
// retrieves or creates a defaultEndpoint using mongoose
// TODO use pre-generated keys every time from db
var getDefaultEndpoint = new Promise(function(resolve, reject) {
  // define endpoint schema
  var endpointSchema = new mongoose.Schema({
      name: String,
      number: Number,
      registrationId: Number,
      signature: String
  });

  // use mongoose encryption
  endpointSchema.plugin(encrypt, {
      encryptionKey: encKey,
      signingKey: sigKey,
      excludeFromEncryption: ['name', 'number']
  });
  // This adds _ct and _ac fields to the schema, as well as pre 'init' and pre 'save' middleware,
  // and encrypt, decrypt, sign, and authenticate instance methods

  // define "Endpoint" model
  Endpoint = mongoose.model('Endpoint', endpointSchema);

  defaultEndpoint = new Endpoint ({ name: 'Default' });
  if (defaultEndpoint) {
    // Store registrationId somewhere durable and safe.
    defaultEndpoint.registrationId = KeyHelper.generateRegistrationId();
    resolve(defaultEndpoint);
  }
  else {
    reject(Error("could not create default endpoint"));
  }
});
```

I know it's ugly... but I'm still prototyping ;)

This is called by a subroutine of my main function, defined below:
```
// Generate Identity + PreKeys
// gets/stores registration ID and KeyPair from/to database
// generates PreKeys and saves in local store
var generateIdentity = new Promise(function(resolve, reject) {
  getDefaultEndpoint.then(function(defaultEndpoint) {
    // TODO break this out into separate function
    KeyHelper.generateIdentityKeyPair().then(function(identityKeyPair) {
      // keyPair -> { pubKey: ArrayBuffer, privKey: ArrayBuffer }
      // Store identityKeyPair somewhere durable and safe (defaultEndpoint)
      store.saveIdentity(defaultEndpoint.registrationId, identityKeyPair);

      KeyHelper.generatePreKey(defaultEndpoint.registrationId).then(function(preKey) {
        store.storePreKey(preKey.keyId, preKey.keyPair);
        // defaultEndpoint.preKey = preKey;
      });

      KeyHelper.generateSignedPreKey(identityKeyPair, defaultEndpoint.registrationId).then(function(signedPreKey) {
        store.storeSignedPreKey(signedPreKey.keyId, signedPreKey.keyPair);
        defaultEndpoint.signature = ab2str(signedPreKey.signature);
        // defaultEndpoint.signedPK = signedPreKey;
      });

      if (store.loadIdentityKey(defaultEndpoint.registrationId)) {
        // Store registrationId somewhere durable and safe.
        resolve(defaultEndpoint);
      }
      else {
        reject(Error("could not generateIdentity"));
      }
    });
  });

  getDefaultEndpoint.catch(function onerror(error) {
    console.log('error getting or creating default endpoint');
  });
});
```

**Comment by DreaminDani** [comment]
If you can't get it up and running, I can create a standalone instance and give you access. Since I'm running from the node command line, and not the browser, it may be difficult to showcase without a server running it.

**Comment by elsehow** [comment]
Thanks for the additional detail.

Any chance you could put together a repo with the relevant code? Or perhaps a gist, if it makes sense.

**Comment by elsehow** [comment]
It might also be helpful if you could factor out the `mongoose`-related code, so it is just native js and `signal-protocol`.

**Comment by DreaminDani** [comment]
Will do :) Might be a while since I'm going on vacation tomorrow. But I'll be sure to link a gist without monsoose refs for easy debugging.

Who knows, maybe just rewriting it will fix the thing? ;)

**Comment by elsehow** [comment]
@d3sandoval any updates on this front?

**Comment by elsehow** [comment]
@d3sandoval I'm closing this issue for now. Please feel free to re-open at any time!!

**Comment by DreaminDani** [comment]
Hi @elsehow sorry it took so long to get back to you. I'm new to javascript-land and I think Promises are throwing off my groove.

I've removed all the references to mongodb but now I can't seem to get the signedPreKey to load when I need it:
`(node:15417) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'pubKey' of undefined`

[Here's a gist](https://gist.github.com/d3sandoval/61491b4dc6d29b46e490810e45dadf79) of what I have, so far. The error is occurring at line 79 of my code, where I attempt to assemble the signedPreKey. I've commented out the rest of the example (encrypting a message and handling identity key conflicts, since I can't seem to properly build the Object that sessionBuilder.processPreKey expects.

I fear I'm overcomplicating things since the example the README.md makes things look so straightforward! I tried borrowing from the test of InMemorySignalProtocolStore.js since that was the closest I could get to a working example of the call/response model that Signal uses to register clients... but I think I'm just circling around the problem of not setting and getting variables in the proper places.

Thanks for the help!

**Comment by elsehow** [comment]
hey @d3sandoval 

Thanks for getting back with this code sample!

Please don't take this the wrong way, but I think you should study up on promises a bit. For example, you have a lot of if/else's to catch errors inside of promises themselves. Promises actually have a nice mechanism for dealing with errors, which will clean up your code quite a bit:

```js
executeMyPromise()
.then(function (result) { return someOtherPromise(result)  })
.then(function (result2) { ... })
.catch(function (someErr) { ... })
```

Errors propagate all the way down the promise chain!

For an example, check out https://github.com/elsehow/signal-stream/blob/master/test/helpers.js#L14-L46 

Lines 14-46 may give you a starting point.

Let me know when you've got another sample and I'll take another look at it!
