### ISSUE TITLE
The npm install signal-protocol command does not work

### ISSUE THREAD

**Issue by ghost** [elsehow/signal-protocol#7]
When I execute the installation command 
npm install signal-protocol
it gives me the following result:
> node-webcrypto-ossl@1.0.25 install C:\xampp\htdocs\chat\node_modules\node-webc
rypto-ossl
> node-gyp rebuild

C:\xampp\htdocs\chat\node_modules\node-webcrypto-ossl>if not defined npm_config_
node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..
\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: La plataforma del proyecto 'nodessl.vcxproj' no
es válida. Plataforma='x64'. Este mensaje puede aparecer porque está intentando
 compilar un proyecto sin un archivo de solución y ha especificado una platafor
ma distinta de la predeterminada que no existe para dicho proyecto. [C:\xampp\h
tdocs\chat\node_modules\node-webcrypto-ossl\build\nodessl.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\chat\node_modules\node-webcrypto-ossl
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "signal-protocol"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-webcrypto-ossl@1.0.25 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-webcrypto-ossl@1.0.25 install script 'node-gyp rebui
ld'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-webcrypto-ossl p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-webcrypto-ossl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-webcrypto-ossl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\chat\npm-debug.log

C:\xampp\htdocs\chat>npm install node-gyp rebuild
npm WARN prefer global node-gyp@3.6.2 should be installed with -g
libsignal-protocol@1.1.2 C:\xampp\htdocs\chat
+-- node-gyp@3.6.2
`-- rebuild@0.1.2
  `-- optimist@0.3.7
    `-- wordwrap@0.0.3

I would like to know if you can help me with the problem
Thank you very much

**Comment by elsehow** [comment]
@Cyraxing - thank you for notifying me of this and opening this issue.

From the stacktrace, this looks like it could be an issue with [node-webcrypto-ossl](https://github.com/PeculiarVentures/node-webcrypto-ossl). 

Do me a favor - in an empty directory, try to

```sh
# create an empty project
npm init -y
npm install node-webcrypto-ossl
```

 and see if you get the same message. Let me know what you find!

**Comment by ghost** [comment]
C:\Empty>npm init -y
Wrote to C:\Empty\package.json:

{
  "name": "Empty",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

C:\Empty>npm install node-webcrypto-ossl

> node-webcrypto-ossl@1.0.25 install C:\Empty\node_modules\node-webcrypto-ossl
> node-gyp rebuild


C:\Empty\node_modules\node-webcrypto-ossl>if not defined npm_config_node_gyp (no
de "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_module
s\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: La plataforma del proyecto 'nodessl.vcxproj' no
es válida. Plataforma='x64'. Este mensaje puede aparecer porque está intentando
 compilar un proyecto sin un archivo de solución y ha especificado una platafor
ma distinta de la predeterminada que no existe para dicho proyecto. [C:\Empty\n
ode_modules\node-webcrypto-ossl\build\nodessl.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Empty\node_modules\node-webcrypto-ossl
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN Empty@1.0.0 No description
npm WARN Empty@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "node-webcrypto-ossl"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-webcrypto-ossl@1.0.25 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-webcrypto-ossl@1.0.25 install script 'node-gyp rebui
ld'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-webcrypto-ossl p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-webcrypto-ossl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-webcrypto-ossl
npm ERR! There is likely additional logging output above.

**Comment by elsehow** [comment]
Looks like the same error to me! 

Please open this issue, with those steps you just did, on [node-webcrypto-ossl](https://github.com/PeculiarVentures/node-webcrypto-ossl). When they fix it, report back here - I'll update the deps and have you try again!

**Comment by ghost** [comment]
In the link I could solve the problem of node-webcrypto-ossl and the code now works.
I installed Git for windows Git-2.13.1.2-64-bit.exe. I executed the following commands:

git clone https://github.com/PeculiarVentures/node-webcrypto-ossl.git --depth 1
cd node-webcrypto-ossl
npm install
node-gyp configure
node-gyp build

Then create a C:\ Empty folder
Copy the node-webcrypto-ossl folder located in the "users" folder.
I ran the command npm install signal-protocol.

Thank you very much!
I am doing a thesis that is the development of a cryptographic chat in Node.js and this code is part of the development, can you tell me their names or pseudonyms to recognize them at work ?. Thank you very much. From Argentina.

**Comment by elsehow** [comment]
Great! Please keep me posted on the development!

Whose handles do you need? `node-webcrypto-ossl` appears to be done by @PeculiarVentures

Signal protocol was written by OpenWhisperSystems: https://en.wikipedia.org/wiki/Signal_Protocol

Closing this issue for now!
